/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan.gui;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import perpustakaan.util.FileManager;
import perpustakaan.model.Buku;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import perpustakaan.model.StatusBuku;

/**
 *
 * @author LENOVO
 */
public class KelolaBuku extends javax.swing.JFrame {

    /**
     * Creates new form KelolaBuku
     * 
     * 
     */
    
    private DefaultTableModel model;
    private FileManager fileManager = new FileManager();
    private List<Buku> listBuku;
    private FileManager fm;
    
    public KelolaBuku() {
        initComponents();
        setLocationRelativeTo(null); // tengah layar
        setPlaceholder();
        fm = new FileManager();
        initTable();
        listBuku = new ArrayList<>();
        loadData();
    }
    
    private void initTable() {
    model = new DefaultTableModel(
        new Object[]{"Kode Buku", "Judul", "Penulis/Edisi", "Tahun Terbit", "Jenis", "Status"}, 0
    );
    DataTabelBuku.setModel(model);
}
    private void setPlaceholder() {
    FieldPencarian.setText("pencarian...");
    FieldPencarian.setForeground(Color.GRAY);

    FieldPencarian.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            if (FieldPencarian.getText().equals("pencarian...")) {
                FieldPencarian.setText("");
                FieldPencarian.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            if (FieldPencarian.getText().isEmpty()) {
                FieldPencarian.setText("pencarian...");
                FieldPencarian.setForeground(Color.GRAY);
            }
        }
    });
}
    
    

    void loadData() {
    model.setRowCount(0); // bersihin tabel

    this.listBuku = fileManager.bacaSemua();
    for (Buku b : listBuku) {
        model.addRow(new Object[]{
            b.getKode(),
            b.getJudul(),
            b.getPenulis(),
            b.getTahun(),
            b.getJenis(),
            b.getStatus()
        });
    }  
  }
   private void cariBuku() {
    String keyword = FieldPencarian.getText().trim().toLowerCase();

    // kalau placeholder atau kosong → tampilkan semua
    if (keyword.equals("pencarian...") || keyword.isEmpty()) {
        loadData();
        return;
    }

    DefaultTableModel model =
        (DefaultTableModel) DataTabelBuku.getModel();
    model.setRowCount(0);

    FileManager fm = new FileManager();
    List<Buku> hasil = fm.cariBuku(keyword);

    if (hasil.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Data tidak ditemukan");
        return;
    }

    for (Buku b : hasil) {
        model.addRow(new Object[]{
            b.getKode(),
            b.getJudul(),
            b.getPenulis(),
            b.getTahun(),
            b.getJenis(),
            b.getStatus()
        });
    }
}
   





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonTambah = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTabelBuku = new javax.swing.JTable();
        FieldPencarian = new javax.swing.JTextField();
        ButtonCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(142, 159, 230));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setText("Kelola Buku");

        ButtonTambah.setText("Tambah");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ButtonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ButtonTambah)
                .addGap(28, 28, 28)
                .addComponent(ButtonHapus)
                .addGap(26, 26, 26)
                .addComponent(ButtonEdit)
                .addGap(28, 28, 28)
                .addComponent(ButtonKembali)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 250, 500));

        jPanel2.setBackground(new java.awt.Color(194, 203, 239));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel2.setText("Tabel Data Buku");

        DataTabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul", "Penulis/Edisi", "Tahun Terbit", "Jenis", "Status"
            }
        ));
        jScrollPane1.setViewportView(DataTabelBuku);
        if (DataTabelBuku.getColumnModel().getColumnCount() > 0) {
            DataTabelBuku.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        FieldPencarian.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        FieldPencarian.setText("Pencarian....");
        FieldPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPencarianActionPerformed(evt);
            }
        });

        ButtonCari.setText("Cari");
        ButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(286, 286, 286))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(FieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        new PopUpTambahBuku().setVisible(true);
        this.dispose();
        loadData();
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void FieldPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPencarianActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        int row = DataTabelBuku.getSelectedRow();

        if (row == -1) {
        JOptionPane.showMessageDialog(this,
        "Pilih buku yang akan dihapus!");
        return;
    }

        String kodeBuku = DataTabelBuku.getValueAt(row, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin menghapus buku ini?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION
    );

        if (confirm == JOptionPane.YES_OPTION) {
        FileManager fm = new FileManager();
        fm.hapusBuku(kodeBuku);

        JOptionPane.showMessageDialog(this,
        "Buku berhasil dihapus");

        loadData(); // refresh JTable
        }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
       int row = DataTabelBuku.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih buku dulu!");
        return;
    }

    Buku bukuDipilih = listBuku.get(row); // ✅ AMAN SEKARANG

    PopUpEditBuku pop = new PopUpEditBuku(bukuDipilih);
    pop.setVisible(true);
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCariActionPerformed
        // TODO add your handling code here:
        cariBuku();
    }//GEN-LAST:event_ButtonCariActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCari;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JTable DataTabelBuku;
    private javax.swing.JTextField FieldPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
