/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan.gui;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import perpustakaan.model.Peminjaman;
import perpustakaan.util.FileManager;

/**
 *
 * @author LENOVO
 */
public class KelolaPeminjaman extends javax.swing.JFrame {

    private DefaultTableModel model;
    private FileManager fileManager = new FileManager();
    private List<Peminjaman> listPeminjaman;
    private FileManager fm;
    
    public KelolaPeminjaman() {
        initComponents();
        setLocationRelativeTo(null); // tengah layar
        setPlaceholder();
        fm = new FileManager();
        initTable();
        listPeminjaman = new ArrayList<>();
        loadData();
    }
    
    private void initTable() {
    model = new DefaultTableModel(
        new Object[]{"ID Anggota", "Nama", "Alamat", "No Telp"}, 0
    );
    DataTabelPeminjaman.setModel(model);
  }
    
    private void setPlaceholder() {
    FieldPencarian.setText("pencarian...");
    FieldPencarian.setForeground(Color.GRAY);

    FieldPencarian.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            if (FieldPencarian.getText().equals("pencarian...")) {
                FieldPencarian.setText("");
                FieldPencarian.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            if (FieldPencarian.getText().isEmpty()) {
                FieldPencarian.setText("pencarian...");
                FieldPencarian.setForeground(Color.GRAY);
            }
        }
    });
}
    
      void loadData() {
    model.setRowCount(0); // bersihin tabel

    this.listPeminjaman = fileManager.bacaSemuaPeminjaman();
    for (Peminjaman p : listPeminjaman) {
        model.addRow(new Object[]{
            p.getIdPinjam(),
            p.getKodeBuku(),
            p.getIdAnggota(),
            p.getTanggalPinjam(),
            p.getTanggalKembali(),
            p.getStatus()
        });
    }  
  }
      
    private void cariPinjam() {
    String keyword = FieldPencarian.getText().trim().toLowerCase();

    // kalau placeholder atau kosong → tampilkan semua
    if (keyword.equals("pencarian...") || keyword.isEmpty()) {
        loadData();
        return;
    }

    DefaultTableModel model =
        (DefaultTableModel) DataTabelPeminjaman.getModel();
    model.setRowCount(0);

    FileManager fm = new FileManager();
    List<Peminjaman> hasil = fm.cariPeminjaman(keyword);

    if (hasil.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Data tidak ditemukan");
        return;
    }

    for (Peminjaman p : hasil) {
        model.addRow(new Object[]{
            p.getIdPinjam(),
            p.getKodeBuku(),
            p.getIdAnggota(),
            p.getTanggalPinjam(),
            p.getTanggalKembali(),
            p.getStatus()
        });
    }
 }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonTambah = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FieldPencarian = new javax.swing.JTextField();
        ButtonPencarian = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTabelPeminjaman = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(142, 159, 230));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setText("Peminjaman");

        ButtonTambah.setText("Tambah");

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(ButtonTambah)
                .addGap(18, 18, 18)
                .addComponent(ButtonHapus)
                .addGap(18, 18, 18)
                .addComponent(ButtonEdit)
                .addGap(18, 18, 18)
                .addComponent(ButtonKembali)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 230, 500);

        jPanel2.setBackground(new java.awt.Color(194, 203, 239));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel2.setText("Tabel Data Peminjaman");

        FieldPencarian.setFont(new java.awt.Font("Book Antiqua", 2, 10)); // NOI18N
        FieldPencarian.setText("Pencarian....");

        ButtonPencarian.setText("Cari");
        ButtonPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPencarianActionPerformed(evt);
            }
        });

        DataTabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pinjam", "Kode Buku", "Id Anggota", "Tanggal Pinjam", "Tanggal kembali ", "Status"
            }
        ));
        jScrollPane1.setViewportView(DataTabelPeminjaman);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(FieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonPencarian)))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPencarian))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(230, 0, 770, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void ButtonPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPencarianActionPerformed
        // TODO add your handling code here:
        cariPinjam();
    }//GEN-LAST:event_ButtonPencarianActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
           int row = DataTabelPeminjaman.getSelectedRow();

        if (row == -1) {
        JOptionPane.showMessageDialog(this,
        "Pilih peminjaman yang akan dihapus!");
        return;
    }

        String kodeBuku = DataTabelPeminjaman.getValueAt(row, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin menghapus ini?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION
    );

        if (confirm == JOptionPane.YES_OPTION) {
        FileManager fm = new FileManager();
        fm.hapusBuku(kodeBuku);

        JOptionPane.showMessageDialog(this,
        "Berhasil dihapus");

        loadData(); // refresh JTable
        }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonPencarian;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JTable DataTabelPeminjaman;
    private javax.swing.JTextField FieldPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
