/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan.gui;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import perpustakaan.util.FileManager;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import perpustakaan.model.BukuPelajaran;
import perpustakaan.model.StatusBuku;

/**
 *
 * @author LENOVO
 */
public class KelolaBuku extends javax.swing.JFrame {

    /**
     * Creates new form KelolaBuku
     * 
     * 
     */
    
    private DefaultTableModel model;
    private FileManager fileManager = new FileManager();
    private List<BukuPelajaran> listBuku;
    private FileManager fm;
    
    public KelolaBuku() {
        initComponents();
        setLocationRelativeTo(null); // tengah layar
        setPlaceholder();
        fm = new FileManager();
        initTable();
        listBuku = new ArrayList<>();
        loadData();
    }
    
    private void initTable() {
    model = new DefaultTableModel(
        new Object[]{"Kode Buku", "Judul", "Penulis/Penyusun", "Tahun Terbit", "Jenis", "Status"}, 0
    );
    DataTabelBuku.setModel(model);
}
    private void setPlaceholder() {
    FieldPencarian.setText("pencarian...");
    FieldPencarian.setForeground(Color.GRAY);

    FieldPencarian.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            if (FieldPencarian.getText().equals("pencarian...")) {
                FieldPencarian.setText("");
                FieldPencarian.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            if (FieldPencarian.getText().isEmpty()) {
                FieldPencarian.setText("pencarian...");
                FieldPencarian.setForeground(Color.GRAY);
            }
        }
    });
}
    
    

    void loadData() {
    model.setRowCount(0); // bersihin tabel

    this.listBuku = fileManager.bacaSemua();
    for (BukuPelajaran b : listBuku) {
        model.addRow(new Object[]{
            b.getKode(),
            b.getJudul(),
            b.getPenulis(),
            b.getTahun(),
            b.getJenis(),
            b.getStatus()
        });
    }
    
    System.out.println("LOAD DATA DIPANGGIL");

   List<BukuPelajaran> list = new FileManager().bacaSemua();
   System.out.println("JUMLAH BUKU = " + list.size());

  }
   private void cariBuku() {
    String keyword = FieldPencarian.getText().trim().toLowerCase();

    // kalau placeholder atau kosong → tampilkan semua
    if (keyword.equals("pencarian...") || keyword.isEmpty()) {
        loadData();
        return;
    }

    DefaultTableModel model =
        (DefaultTableModel) DataTabelBuku.getModel();
    model.setRowCount(0);

    FileManager fm = new FileManager();
    List<BukuPelajaran> hasil = fm.cariBuku(keyword);

    if (hasil.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Data tidak ditemukan");
        return;
    }

    for (BukuPelajaran b : hasil) {
        model.addRow(new Object[]{
            b.getKode(),
            b.getJudul(),
            b.getPenulis(),
            b.getTahun(),
            b.getJenis(),
            b.getStatus()
        });
    }
}
   





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonTambah = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTabelBuku = new javax.swing.JTable();
        FieldPencarian = new javax.swing.JTextField();
        ButtonCari = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 43, 143));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kelola ");

        ButtonTambah.setText("Tambah");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buku");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Buku.png"))); // NOI18N
        jLabel4.setText("\\");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 56, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(ButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(jLabel3)))
                            .addGap(47, 47, 47))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(35, 35, 35))))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addGap(33, 33, 33)
                    .addComponent(ButtonTambah)
                    .addGap(31, 31, 31)
                    .addComponent(ButtonHapus)
                    .addGap(32, 32, 32)
                    .addComponent(ButtonKembali)
                    .addGap(50, 50, 50))
            );

            getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 250, 500));

            jPanel2.setBackground(new java.awt.Color(193, 230, 248));

            jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
            jLabel2.setText("Tabel Data Buku");

            DataTabelBuku.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Kode Buku", "Judul", "Penulis/Penyusun", "Tahun Terbit", "Jenis", "Status"
                }
            ));
            jScrollPane1.setViewportView(DataTabelBuku);
            if (DataTabelBuku.getColumnModel().getColumnCount() > 0) {
                DataTabelBuku.getColumnModel().getColumn(0).setPreferredWidth(25);
            }

            FieldPencarian.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
            FieldPencarian.setText("Pencarian....");
            FieldPencarian.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    FieldPencarianActionPerformed(evt);
                }
            });

            ButtonCari.setText("Cari");
            ButtonCari.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ButtonCariActionPerformed(evt);
                }
            });

            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/long-row-colorful-books-removebg-preview.png"))); // NOI18N
            jLabel5.setText("\\");

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/long-row-colorful-books-removebg-preview.png"))); // NOI18N
                jLabel6.setText("\\");

                    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/KelolaBuku-removebg-preview.png"))); // NOI18N

                    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                    jPanel2.setLayout(jPanel2Layout);
                    jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap(21, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(286, 286, 286))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(FieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(ButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addGap(47, 47, 47)
                            .addComponent(jLabel6)
                            .addContainerGap())
                    );
                    jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    );

                    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 770, 500));

                    pack();
                }// </editor-fold>//GEN-END:initComponents

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        new PopUpTambahBuku().setVisible(true);
        this.dispose();
        loadData();
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void FieldPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPencarianActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        int row = DataTabelBuku.getSelectedRow();

        if (row == -1) {
        JOptionPane.showMessageDialog(this,
        "Pilih buku yang akan dihapus!");
        return;
    }

        String kodeBuku = DataTabelBuku.getValueAt(row, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin menghapus buku ini?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION
    );

        if (confirm == JOptionPane.YES_OPTION) {
        FileManager fm = new FileManager();
        fm.hapusBuku(kodeBuku);

        JOptionPane.showMessageDialog(this,
        "Buku berhasil dihapus");

        loadData(); // refresh JTable
        }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCariActionPerformed
        // TODO add your handling code here:
        cariBuku();
    }//GEN-LAST:event_ButtonCariActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCari;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JTable DataTabelBuku;
    private javax.swing.JTextField FieldPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
