/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan.gui;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import perpustakaan.model.Peminjaman;
import perpustakaan.util.FileManager;

/**
 *
 * @author LENOVO
 */

// class jfrane kelolapeminjaman
public class KelolaPeminjaman extends javax.swing.JFrame {

    private DefaultTableModel model;
    private FileManager fileManager = new FileManager();
    private List<Peminjaman> listPeminjaman;
    private FileManager fm;
    public static KelolaPeminjaman instance;
    
    public KelolaPeminjaman() {
        initComponents();
        setLocationRelativeTo(null); // tengah layar
        setPlaceholder();
        fm = new FileManager();
        initTable();
        listPeminjaman = new ArrayList<>();
        instance = this; 
        loadData();
    }
    
    // method membaca data pad jtable
    private void initTable() {
    model = new DefaultTableModel(
        new Object[]{"IdPinjam", "KodeBuku", "IdAnggota", "TanggalPinjam", "Status"}, 0
    );
    DataTabelPeminjaman.setModel(model);
  }
    
    private void setPlaceholder() {
    FieldPencarian.setText("pencarian...");
    FieldPencarian.setForeground(Color.GRAY);

    FieldPencarian.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            if (FieldPencarian.getText().equals("pencarian...")) {
                FieldPencarian.setText("");
                FieldPencarian.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            if (FieldPencarian.getText().isEmpty()) {
                FieldPencarian.setText("pencarian...");
                FieldPencarian.setForeground(Color.GRAY);
            }
        }
    });
}
    
    // method refreh
    void loadData() {
    model.setRowCount(0);

    this.listPeminjaman = fm.bacaSemuaPeminjaman(); // ← PAKAI fm
    for (Peminjaman p : listPeminjaman) {
        model.addRow(new Object[]{
            p.getIdPinjam(),
            p.getIdAnggota(),
            p.getKodeBuku(),
            p.getTanggalPinjam(),
            p.getStatus()
        });
    }
}

    // method pencarian pinjam  
    private void cariPinjam() {
    String keyword = FieldPencarian.getText().trim().toLowerCase();

    // kalau placeholder atau kosong → tampilkan semua
    if (keyword.equals("pencarian...") || keyword.isEmpty()) {
        loadData();
        return;
    }

    DefaultTableModel model =
        (DefaultTableModel) DataTabelPeminjaman.getModel();
    model.setRowCount(0);

    FileManager fm = new FileManager();
    List<Peminjaman> hasil = fm.cariPeminjaman(keyword);

    if (hasil.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Data tidak ditemukan");
        return;
    }

    for (Peminjaman p : hasil) {
        model.addRow(new Object[]{
            p.getIdPinjam(),
            p.getKodeBuku(),
            p.getIdAnggota(),
            p.getTanggalPinjam(),
            p.getStatus()
        });
    }
 }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonTambahPinjam = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonKembalikan = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FieldPencarian = new javax.swing.JTextField();
        ButtonPencarian = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTabelPeminjaman = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 43, 143));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Peminjaman");

        ButtonTambahPinjam.setText("Tambah Pinjam");
        ButtonTambahPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahPinjamActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonKembalikan.setText("Kembalikan");
        ButtonKembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembalikanActionPerformed(evt);
            }
        });

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kelola");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Peminjaman.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonKembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambahPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ButtonTambahPinjam)
                .addGap(18, 18, 18)
                .addComponent(ButtonKembalikan)
                .addGap(18, 18, 18)
                .addComponent(ButtonHapus)
                .addGap(18, 18, 18)
                .addComponent(ButtonKembali)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        jPanel2.setBackground(new java.awt.Color(193, 230, 248));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel2.setText("Tabel Data Peminjaman");

        FieldPencarian.setFont(new java.awt.Font("Book Antiqua", 2, 10)); // NOI18N
        FieldPencarian.setText("Pencarian....");

        ButtonPencarian.setText("Cari");
        ButtonPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPencarianActionPerformed(evt);
            }
        });

        DataTabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPinjam", "KodeBuku", "IdAnggota", "TanggalPinjam", "Status"
            }
        ));
        jScrollPane1.setViewportView(DataTabelPeminjaman);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/long-row-colorful-books-removebg-preview.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/KelolaPeminjaman-removebg-preview.png"))); // NOI18N
        jLabel7.setText("\\");

            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/long-row-colorful-books-removebg-preview.png"))); // NOI18N

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(243, 243, 243)
                    .addComponent(jLabel2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(0, 28, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ButtonPencarian)))
                    .addGap(29, 29, 29))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addGap(36, 36, 36)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ButtonPencarian)
                        .addComponent(FieldPencarian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 760, 500));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
          int row = DataTabelPeminjaman.getSelectedRow();

        if (row == -1) {
        JOptionPane.showMessageDialog(this,
        "Pilih peminjaman yang akan dihapus!");
        return;
    }

        String idPinjam = DataTabelPeminjaman.getValueAt(row, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin menghapus ini?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION
    );

        if (confirm == JOptionPane.YES_OPTION) {
        FileManager fm = new FileManager();
        fm.hapusPeminjaman(idPinjam);

        JOptionPane.showMessageDialog(this,
        "Berhasil dihapus");
        
         loadData(); // refresh JTable
        }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();

    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void ButtonPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPencarianActionPerformed
        // TODO add your handling code here:
        cariPinjam();
    }//GEN-LAST:event_ButtonPencarianActionPerformed

    private void ButtonKembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembalikanActionPerformed

     int row = DataTabelPeminjaman.getSelectedRow();
    if (row == -1) {
    JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu");
    return;
}

    String idPinjam = DataTabelPeminjaman.getValueAt(row, 0).toString();
    String kodeBuku = DataTabelPeminjaman.getValueAt(row, 2).toString();

     FileManager fm = new FileManager();
     fm.kembalikanBuku(idPinjam, kodeBuku);

    loadData(); // refresh JTable

    JOptionPane.showMessageDialog(this,
    "Buku berhasil dikembalikan"
);

    }//GEN-LAST:event_ButtonKembalikanActionPerformed

    private void ButtonTambahPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahPinjamActionPerformed
        // TODO add your handling code here:
        new PopUpTambahPinjam().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonTambahPinjamActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonKembalikan;
    private javax.swing.JButton ButtonPencarian;
    private javax.swing.JButton ButtonTambahPinjam;
    private javax.swing.JTable DataTabelPeminjaman;
    private javax.swing.JTextField FieldPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
